create table if not exists public.offers (
 id bigint generated by default as identity primary key,
 tracker_id uuid not null references public.trackers(id) on delete cascade,
 retailer text not null,
 title text,
 url text not null,
 price numeric not null,
 shipping numeric not null default 0,
 delivered_price numeric not null,
 currency text not null default 'SAR',
 in_stock boolean not null default true,
 source text,
 checked_at timestamptz not null default now()
);
create index if not exists offers_tracker_price_idx on public.offers(tracker_id, delivered_price asc);
alter table public.offers enable row level security;
drop policy if exists "public read offers" on public.offers;
create policy "public read offers" on public.offers for select using (true);
