create extension if not exists pgcrypto;
create table if not exists public.trackers (
 id uuid primary key default gen_random_uuid(), name text not null, country text not null default 'SA',
 currency text not null default 'SAR', url text, urls jsonb not null default '[]'::jsonb,
 threshold_pct numeric not null default 15 check (threshold_pct between 1 and 90), target_price numeric,
 active boolean not null default true, last_status text, last_error text, created_at timestamptz not null default now()
);
create table if not exists public.observations (
 id bigint generated by default as identity primary key, tracker_id uuid not null references public.trackers(id) on delete cascade,
 retailer text not null, title text, url text not null, price numeric not null, shipping numeric not null default 0,
 delivered_price numeric not null, currency text not null default 'SAR', in_stock boolean not null default true,
 baseline numeric, discount_pct numeric, is_deal boolean not null default false, source text,
 checked_at timestamptz not null default now()
);
create index if not exists observations_tracker_checked_idx on public.observations(tracker_id, checked_at desc);
alter table public.trackers enable row level security;
alter table public.observations enable row level security;
drop policy if exists "public read trackers" on public.trackers;
create policy "public read trackers" on public.trackers for select using (true);
drop policy if exists "public insert trackers" on public.trackers;
create policy "public insert trackers" on public.trackers for insert with check (country='SA' and char_length(name) between 2 and 180);
drop policy if exists "public delete trackers" on public.trackers;
create policy "public delete trackers" on public.trackers for delete using (true);
drop policy if exists "public read observations" on public.observations;
create policy "public read observations" on public.observations for select using (true);
