const cfg=window.PRICE_INTEL_CONFIG||{},$=id=>document.getElementById(id);
const configured=()=>cfg.supabaseUrl&&!cfg.supabaseUrl.includes('REPLACE_')&&cfg.supabaseAnonKey&&!cfg.supabaseAnonKey.includes('REPLACE_');
const headers=()=>({apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`,'Content-Type':'application/json'});
const api=(t,q='')=>`${cfg.supabaseUrl.replace(/\/$/,'')}/rest/v1/${t}${q}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`SAR ${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const fmtTime=v=>v?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
const pct=n=>`${Number(n||0).toFixed(1)}%`;
async function getTrackers(){const r=await fetch(api('trackers','?active=eq.true&select=*&order=created_at.desc'),{headers:headers()});if(!r.ok)throw new Error(await r.text());return r.json()}
async function getObs(){const r=await fetch(api('observations','?select=*&order=checked_at.desc&limit=1000'),{headers:headers()});if(!r.ok)throw new Error(await r.text());return r.json()}
function setMsg(t,e=false){$('formMsg').textContent=t;$('formMsg').className=`msg ${e?'error':'ok'}`}
async function addTracker(){const name=$('itemName').value.trim(),url=$('itemUrl').value.trim();if(!configured())return setMsg('Backend is not configured yet. Add Supabase URL + anon key in config.js.',true);if(!name)return setMsg('Item name is required.',true);if(url){try{new URL(url)}catch{return setMsg('Enter a valid product URL, or leave it blank for automatic discovery.',true)}}const payload={name,country:'SA',currency:'SAR',url:url||null,urls:url?[url]:[],threshold_pct:Number($('threshold').value||15),target_price:Number($('targetPrice').value)||null,last_status:url?'queued':'discovery_queued',last_error:null};const r=await fetch(api('trackers'),{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok)return setMsg(`Could not create tracker: ${await r.text()}`,true);$('itemName').value='';$('itemUrl').value='';$('targetPrice').value='';setMsg(url?'Tracker saved. It will be checked by the next scheduled crawl.':'Tracker saved in discovery mode. Serper will find Saudi listings on the next crawl.');await render()}
async function removeTracker(id){if(!confirm('Remove this tracker and its history?'))return;const r=await fetch(api('trackers',`?id=eq.${encodeURIComponent(id)}`),{method:'DELETE',headers:headers()});if(!r.ok)return alert(await r.text());render()}
function sparkSvg(rows){if(!rows.length)return'<div class="muted">Waiting for first crawl</div>';const vals=rows.slice(-30).map(x=>Number(x.delivered_price));if(vals.length===1)return`<svg class="spark-svg" viewBox="0 0 300 92"><line class="spark-bg" x1="0" y1="78" x2="300" y2="78"/><circle class="spark-dot" cx="150" cy="46" r="4"/></svg>`;const min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min),pts=vals.map((v,i)=>{const x=8+i*(284/(vals.length-1)),y=78-((v-min)/span)*62;return`${x.toFixed(1)},${y.toFixed(1)}`}).join(' '),last=pts.split(' ').at(-1).split(',');return`<svg class="spark-svg" viewBox="0 0 300 92"><line class="spark-bg" x1="0" y1="78" x2="300" y2="78"/><polyline class="spark-line" points="${pts}"/><circle class="spark-dot" cx="${last[0]}" cy="${last[1]}" r="4"/></svg>`}
function statusBadge(t,cur){if(t.last_status==='error')return'<span class="badge error">ERROR</span>';if(cur?.is_deal)return'<span class="badge deal">DEAL</span>';return'<span class="badge normal">WATCHING</span>'}
function dealReason(t,cur){if(!cur)return'Waiting for market data';if(t.target_price&&Number(cur.delivered_price)<=Number(t.target_price))return`Target met: ${money(t.target_price)}`;if(Number(cur.discount_pct)>0)return`${pct(cur.discount_pct)} below baseline`;return'No baseline discount yet'}
function trackerCard(t,rows){const cur=rows.at(-1),vals=rows.map(r=>Number(r.delivered_price)).filter(Number.isFinite),low=vals.length?Math.min(...vals):null,high=vals.length?Math.max(...vals):null,avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,delta=cur&&cur.baseline?((Number(cur.delivered_price)-Number(cur.baseline))/Number(cur.baseline))*100:0,deltaClass=delta<0?'good':delta>0?'bad':'flat',sourceUrl=cur?.url||t.url||null;return`<article class="card"><div class="cardtop"><div><h3>${esc(t.name)}</h3><p class="meta">${esc(cur?.retailer||'Pending first crawl')} · ${esc(t.last_status||'queued')}</p></div>${statusBadge(t,cur)}</div><div class="price-row"><div><div class="price">${cur?money(cur.delivered_price):'—'}</div><div class="delta ${deltaClass}">${cur?dealReason(t,cur):'No observation yet'}</div></div><div class="meta">${cur?`Last checked ${fmtTime(cur.checked_at)}`:'—'}</div></div><div class="metrics"><div class="metric"><span>Baseline</span><strong>${cur?money(cur.baseline):'—'}</strong></div><div class="metric"><span>Target</span><strong>${t.target_price?money(t.target_price):'—'}</strong></div><div class="metric"><span>Observed low</span><strong>${low!=null?money(low):'—'}</strong></div><div class="metric"><span>Observed high</span><strong>${high!=null?money(high):'—'}</strong></div><div class="metric"><span>Average</span><strong>${avg!=null?money(avg):'—'}</strong></div><div class="metric"><span>Observations</span><strong>${rows.length}</strong></div><div class="metric"><span>Threshold</span><strong>${pct(t.threshold_pct)}</strong></div><div class="metric"><span>Source</span><strong>${esc(cur?.source||'—')}</strong></div></div><div class="chart-wrap">${sparkSvg(rows)}</div><div class="card-actions"><div class="links">${sourceUrl?`<a href="${esc(sourceUrl)}" target="_blank" rel="noopener">Open latest source</a>`:''}${t.url&&t.url!==sourceUrl?`<a href="${esc(t.url)}" target="_blank" rel="noopener">Open tracker URL</a>`:''}</div><button class="remove" onclick="removeTracker('${t.id}')">Remove</button></div>${t.last_error?`<p class="error small">${esc(t.last_error)}</p>`:''}</article>`}
function renderSnapshot(trackers,obs){const latest=trackers.map(t=>{const rs=obs.filter(o=>o.tracker_id===t.id).sort((a,b)=>new Date(a.checked_at)-new Date(b.checked_at));return rs.at(-1)}).filter(Boolean),prices=latest.map(x=>Number(x.delivered_price)).filter(Number.isFinite),retailers=new Set(latest.map(x=>x.retailer).filter(Boolean)),healthy=trackers.filter(t=>t.last_status==='ok').length;$('portfolioSnapshot').innerHTML=`<div class="snapshot-item"><span>Tracked value</span><strong>${prices.length?money(prices.reduce((a,b)=>a+b,0)):'—'}</strong></div><div class="snapshot-item"><span>Retailers seen</span><strong>${retailers.size}</strong></div><div class="snapshot-item"><span>Healthy trackers</span><strong>${healthy}/${trackers.length}</strong></div>`}
function renderActivity(obs){const rows=[...obs].sort((a,b)=>new Date(b.checked_at)-new Date(a.checked_at)).slice(0,6);$('recentActivity').innerHTML=rows.length?rows.map(o=>`<div class="activity-row"><div><strong>${esc(o.title||o.retailer||'Observation')}</strong><br><span>${esc(o.retailer||'Unknown source')} · ${money(o.delivered_price)}</span></div><span>${fmtTime(o.checked_at)}</span></div>`).join(''):'<p class="muted">No crawl history yet.</p>'}
async function render(){if(!configured()){$('backendStatus').textContent='Needs Supabase config';$('backendDot').className='dot warn';$('trackerList').innerHTML='<p class="muted">Deploy the Supabase schema, then put the public project URL and anon key in <code>config.js</code>.</p>';return}$('backendStatus').textContent='Connected';$('backendDot').className='dot live';$('lastRefresh').textContent=`refreshed ${fmtTime(new Date())}`;try{const[trackers,obs]=await Promise.all([getTrackers(),getObs()]),by={};for(const o of obs)(by[o.tracker_id]??=[]).push(o);for(const id in by)by[id].sort((a,b)=>new Date(a.checked_at)-new Date(b.checked_at));let deals=0,best=0;for(const t of trackers){const cur=(by[t.id]||[]).at(-1);if(cur?.is_deal)deals++;best=Math.max(best,Number(cur?.discount_pct||0))}$('trackerList').innerHTML=trackers.map(t=>trackerCard(t,by[t.id]||[])).join('')||'<p class="muted">No trackers yet.</p>';$('trackedCount').textContent=trackers.length;$('dealCount').textContent=deals;$('bestDiscount').textContent=`${best.toFixed(1)}%`;$('observationCount').textContent=obs.length;$('trackedDetail').textContent=`${trackers.filter(t=>t.last_status==='ok').length} healthy`;$('dealDetail').textContent=deals?`${deals} target/baseline trigger${deals===1?'':'s'}`:'No active deal triggers';$('bestSavingDetail').textContent='vs recent median baseline';$('observationDetail').textContent=obs.length?`latest ${fmtTime(obs[0]?.checked_at)}`:'3 checks / day';$('productSummary').textContent=`${trackers.length} product${trackers.length===1?'':'s'}`;renderSnapshot(trackers,obs);renderActivity(obs)}catch(e){$('backendStatus').textContent='Backend error';$('backendDot').className='dot warn';$('trackerList').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
$('addTracker').addEventListener('click',addTracker);$('refresh').addEventListener('click',render);window.removeTracker=removeTracker;render();
