window.PRICE_INTEL_CONFIG = {
  supabaseUrl: "https://nckhnwqsbtpghzbpeedk.supabase.co",
  supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ja2hud3FzYnRwZ2h6YnBlZWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3OTIxMDcsImV4cCI6MjEwMjM2ODEwN30.q2fFU6XC46wOZG-g6lZQqCdQGtvjaiwaGs7rtOnGwL4"
};
